# Generated by Django 4.0.5 on 2022-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userauth_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
